### ISSUE TITLE
When pokemon are caught close together the 2nd pokemon displays the same stats as the first

### ISSUE THREAD

**Issue by Cardbored** [SwipeX/PokeMate#129]
An example: http://image.prntscr.com/image/ff3e9e077fa14d8984dc14bd897606ec.png

**Comment by RobertMcCoy** [comment]
My assumption on this is that since pokemon can be caught in short succession, the CatchPokemon.java isn't getting the most recent pokemon in the list, but it is populating the right name because it is using the target for the name. Will need to look at this a bit more later, won't be able to for an hour or so.

**Comment by SwipeX** [comment]
check with 2cf423f38977af36c0dcc7da0d2e20c8e114f116
