### ISSUE TITLE
Some pokemon are not transfered

### ISSUE THREAD

**Issue by QuarkyUp** [SwipeX/PokeMate#169]
First of all, thank you for your hard work. This is a gold mine of information !

I am experiencing an issue about Pokemon transfer. Most of Raticate, Zubat, Rattata, Pidgeotto are not transfered, so I have a lot of them.
On the contrary, **all other captured pokemon** are transfered properly: I just keep one of them if I have more than one (e.g. If I have two Pikachu, the weakest is transfered).

Has anyone experienced a similar issue ?

Here is my config file if it helps.

```
# PTC/Google login credentials
username=
password=
# Location by name: e.g. "Sydney" or "W12 8LP" or "Trafalgar Square, London" - set to true to use
use-location-name=true
location-by-name=""
#Lat/Long
latitude=
longitude=
#Preferred throw item
preferred_ball=ITEM_POKE_BALL
#Google maps API key for walking
api-key=
#What IV% to keep pokemon at
iv-ratio=90
#What CP to keep pokemon above
min-cp=250
#show user interface
show=true
# should the bot EVER drop items (true/false)
drop_items=true
# Meters per second
speed=1.30
# Automatic evolving 
automatic-evolving=true
#Range to walk in, VERY sensitive
range=.027
#points in the map path
map-points=100
# Only whitelist certain pokemons
whitelisted-pokemon=10,13,16,17,19,21,41
# List of Pokémons ids to NEVER transfer, separated by commas.
never-transfer=
# Enable events notifications on console output
console_notification=true
# Enable toast notifications on UI (only if UI is enabled)
ui_notification=true
#Enable popup notifications
sys_notification=true
# Enable auto eggs incubating
eggs_incubating=true
# Enable auto eggs hatching
eggs_hatching=true
# Items to drop (remove from this list if you want to keep it, note that inventory management will now be left up to you, as it could be possible to run out of pokeballs)
drop_item_list=ITEM_POTION,ITEM_SUPER_POTION,ITEM_MAX_POTION,ITEM_HYPER_POTION,ITEM_RAZZ_BERRY,ITEM_REVIVE,ITEM_MAX_REVIVE
# Minimum CP for a pokemon to have a pop-up message (All pokemon that are caught will still be logged)
minimum_cp_for_ui_message=0
```

**Comment by kyleshrader** [comment]
Your min-cp is pretty low. you will keep all pokemon with cp 250 and above.

**Comment by kyleshrader** [comment]
When transferring pokemon, it will always keep
1. The highest CP
2. Any above the CP threshold
3. Any above the IV threshold
4. Any listed in never-transfer

**Comment by QuarkyUp** [comment]
So if I have a Pokemon with a CP lower than my CP threshold and an IV lower than my threshold, but I only got one of that pokemon it will keep it anyway ?

**Comment by kylestev** [comment]
@QuarkyUp you would need to list its number under the `never-transfer` configuration option for it to keep it.

**Comment by arkdelkaos** [comment]
@kylestev I think that @QuarkyUp is trying to ask _"why there are pokemons stored, even when they are under the cp and iv's threshold, and not white-listed"_
I think that the bot save one of every kind, with possible evolutions, just to be evolved when having enough candies.
And then, if that's why, some questions arise:
- If a better pokemon that those "evolve-able" saved, with better IV's and/or CP, get caught: Do the bot transfer the 'old' one, and store the new one?
- Its there a way to mark some pokemon ID's as "not to evolve"? Because wasting 400 candies into a bad magikarp may hurt XD I didn't saw the option on config, and it could be great to just keep storing the best pokemon of one family, but save the candies.

**Comment by mark3717** [comment]
It should always transfer pokemon below the `min-iv` setting, unless it's CP is (equal/)higher than the `min-cp` setting. However it still keeps 250cp-ish pokemon with an IV% below my `min-iv` setting...

my settings: `min-iv=80` and `min-cp=1000`

**Comment by gsisso** [comment]
@mark3717 at the moment it is designed that it will also keep at least 1 pokemon so if you only have 1 pidgey for example ,it doesn't matter what cp or iv % he has he won't be released.

you can always change that at ReleasePokemon.java  instead of `list.indexOf(p) < list.size() - 1` do `list.indexOf(p) < list.size()`

you should be aware that this might remove some rare pokemons you have so do this change at your own risk

**Comment by SippieCup** [comment]
Question has been adequately answered, closing thread.
