### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by elmagow** [SwipeX/PokeMate#221]
Ui does not refresh correctly.

Player icon, blue square and red line disappear when the UI is refreshed.

**Comment by BurakDev** [comment]
What do you mean by refresh ? Right click => refresh ?

**Comment by SippieCup** [comment]
This happens when navigating with pokestops and you get Softbanned 2.0

Since no pokestops appear, it cannot generate a path for the trainer to walk on. I suggest switching to streets navigation for the time being.

**Comment by elmagow** [comment]
I think I didnt describe it really clearly.

The red line, the player icon, and blue square are "flashing"(appear/disappear) when the UI "refresh" itself to update its position etc. But everything is working fine, no softban. I'm at a steady 70kxp/h

**Comment by jinkawasaki333** [comment]
@SippieCup Could you elaborate more about Softban 2.0 please? Did they update the softban?

**Comment by SippieCup** [comment]
It seems that theres a new implementation of softbans, which is a much better way of reducing server load and punishing the user than the previous method.

Now, if you get the new softban 2.0. - Any query for pokemon, pokestops, or gyms will result the in server saying there are none around you. Since the client sees that there is nothing around.. it will not continue querying the server for all the additional information like before. Furthermore, this technically fixes the softban bypass. I think I have a solution to bypass Softban 2.0 as well.

Alternatively, this softban could just be the byproduct of a new server architecture and an increase in sharding between locations.. But I think its was intentionally done.

**Comment by bolds07** [comment]
@SippieCup I dont think this is a "feature" of niantic server.... probably this situation can happen because of several conditions [maybe softban is one of them, but not the only, server loads is very problable also]

Just keep in mind, softban is the easiest thing to test, just create one new account and see if it happens... i've 80 accounts and all of them are issued by this problem on this weekend, so to be complety sure i created a new one, and the same happens...

**Comment by jinkawasaki333** [comment]
@bolds07 Not related to this topic, but how did you manage to create 80 accounts? Do you have bot for it?

**Comment by SippieCup** [comment]
There are generators available on github.com. 

This now going off topic, I'm closing this thread. Please join slack if you want to discuss matters like this.

**Comment by bolds07** [comment]
@jinkawasaki333 to create a fake account on ptc, is just a matter of fill a 6 fields form...
