### ISSUE TITLE
DropItems Started

### ISSUE THREAD

**Issue by SSinischo** [SwipeX/PokeMate#223]
With the current version, my character will move around but not interact with pokemon or pokestops.  The console is spanning "DropItems Started" every few seconds or so. 
drop_item_list is the default

**Comment by SippieCup** [comment]
Thats just a debug line that was left in.

You are softbanned 2.0 from teleporting. This new softban, rather than making stuff run away or not able to be used, just makes it so nothing appears. stay logged out for a bit and then go to that location, or pick a location closer to where you actually live.
